# Generated by Django 4.0.9 on 2023-03-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_brand_colour_size_products_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colour',
            name='colour_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
