# Generated by Django 4.0.9 on 2023-03-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_remove_products_image_productvariation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='image',
            field=models.ImageField(null=True, upload_to='images/products/'),
        ),
    ]
