# Generated by Django 4.0.10 on 2023-05-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='discount',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariation',
            name='sell_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
