# Generated by Django 4.0.10 on 2023-05-22 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_productvariation_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='sell_price',
        ),
    ]
