# Generated by Django 4.0.10 on 2023-05-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_productvariation_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='variation_title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
