# Generated by Django 4.0.10 on 2023-05-23 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0022_rename_variation_title_productvariation_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='discount',
        ),
    ]
