# Generated by Django 4.0.10 on 2023-05-23 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0023_remove_productvariation_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='product_title',
        ),
    ]
